prompts = [
    'The quick brown fox jumps over a lazy dog.',
    'Mr. Jock, TV quiz PhD., bags few lynx.',
    'Two driven jocks help fax my big quiz.',
    'Waltz, nymph, for quick jigs vex Bud.',
    'My girl wove six dozen plaid jackets before she quit.',
    'Sixty zippers were quickly picked from the woven jute bag.',
    'Sphinx of black quartz, judge my vow.',
    'A wizard’s job is to vex chumps quickly in fog.',
    'Brown jars prevented the mixture from freezing too quickly.',
    'How vexingly quick daft zebras jump!',
    'Watch “Jeopardy!”, Alex Trebek’s fun TV quiz game.',
    'Jackdaws love my big sphinx of quartz.',
    'GQ’s oft lucky whiz Dr. J, ex-NBA MVP.',
    'We promptly judged antique ivory buckles for the next prize.',
    'Glib jocks quiz nymph to vex dwarf.',
    'When zombies arrive, quickly fax Judge Pat.',
    'Waxy and quivering, jocks fumble the pizza.',
    'The jay, pig, fox, zebra and my wolves quack!',
    'Pack my box with five dozen liquor jugs.',
    'The five boxing wizards jump quickly.',
    'Farmer jack realized that big yellow quilts were expensive.',
    'Relaxing in basins at the end of inlets terminates the endless tests from the box.',
    'Carved symbols in a mountain hollow on the bank of an inlet irritated an eccentric person.',
    'Cross valley and plain to steal coins from Saudi mint.',
    'An Abyssinian fly playing a Celtic violin was annoyed by trashy flags on which were the Hebrew letter qoph.',
    'A short brimless felt hat barely blocks out the sound of a Celtic violin.',
    'A grass-plains wryneck climbs upon a male yak-cattle hybrid that was donated under Islamic law.',
    'Signage indicating endowments for industrial diamonds annoy filth-spreading genies.'
    'Being bounced around quickly annoyed the disheveled taxi drivers.',
    'Public relations agent asks sports room, when do television disc jockeys fight?',
    'Making a high-pitched sound, short athletes annoy their white blood plasma and an Islamic saint.',
    'Making a high-pitched sound, annoyed mountain basin insect sticks Hebrew letter.',
    'European bison of a shrubby African plain make digital image files of Semitic letters from valley wrynecks.',
    'Fox nymphs grab quick-jived waltz.',
    'Both fickle dwarves jinx my pig quiz.',
    'Two driven jocks help fax my big quiz.',
    'How quickly daft jumping zebras vex.',
    'Blowzy red vixens fight for a quick jump.',
    'Quizzical twins proved my hijack-bug fix.',
    'Woven silk pyjamas exchanged for blue quartz.',
    'The lazy major was fixing Cupid’s broken quiver.',
    'The quick onyx goblin jumps over the lazy dwarf.',
    'As quirky joke, chefs won’t pay devil magic zebra tax.',
    'Six big devils from Japan quickly forgot how to waltz.',
    'Big July earthquakes confound zany experimental vow.',
    'Cute, kind, jovial, foxy physique, amazing beauty? Wowser!',
    'Just poets wax boldly as kings and queens march over fuzz.',
    'Crazy Frederick bought many very exquisite opal jewels.',
    'Just keep examining every low bid quoted for zinc etchings.'
    'Puny lazy squads joke of a worthy moving xebec.',
    'A hot fowl amazed by quacked ravens jinxing a pub.',
    'Are those shy Eurasian footwear, cowboy chaps, or jolly earthmoving headgear?',
    'With tenure, Suzie’d have all the more leisure for yachting, but her publications are no good.'
]
